#!/bin/bash

DATE=`stat /etc/adblock |grep Modify`
DATE=${DATE:8:10}

if [ $(date '+%Y-%m-%d') = $DATE ]
	then exit
fi

echo 255 > /sys/class/leds/rango:amber:wan/brightness

addr=(	'http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext' \
	'https://adaway.org/hosts.txt' \
	'https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt' \
	'http://www.dshield.org/feeds/suspiciousdomains_Low.txt' \
	'hosts-file.net/ad_servers.txt' \
	'https://mirror.cedia.org.ec/malwaredomains/justdomains' \
	'http://www.malwaredomainlist.com/hostslist/hosts.txt' \
	'https://openphish.com/feed.txt' \
	'https://palevotracker.abuse.ch/blocklists.php?download=domainblocklist' \
	'https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt' \
	'https://easylist-downloads.adblockplus.org/rolist+easylist.txt' \
	'https://easylist-downloads.adblockplus.org/ruadlist+easylist.txt' \
	'http://securemecca.com/Downloads/hosts.txt' \
	'https://raw.githubusercontent.com/Dawsey21/Lists/master/main-blacklist.txt' \
	'https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/win10/spy.txt' \
	'https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist' \
	'http://someonewhocares.org/hosts/hosts' \
	'http://winhelp2002.mvps.org/hosts.txt' \
	'http://sysctl.org/cameleon/hosts')

cd /home/tmp

for ((i=0; i<${#addr[*]}; i++)); do

	wget ${addr[$i]} --no-check-certificate -O hosts_list.$i

	sed -i 's/0.0.0.0/127.0.0.1/' hosts_list.$i
	sed -i '/127.0.0.1/{x;p;x;G;}' hosts_list.$i
	sed -i 's/\t/ /g' hosts_list.$i
	sed -i 's/  / /g' hosts_list.$i

done

in="hosts_list.*" && out="/etc/adblock" && host='127.0.0.1'

echo "#/ip dns static" > $out && grep '127.0.0.1 ' $in \
	| grep -v '^#' \
        | cut -d' ' -f 2 \
        | grep . \
	| tr -d '\r' \
	| sort -u \
	| sed '$!N; /^\(.*\)\n\1$/!P; D' \
	| sed -e '/r.mail.ru/d' \
	| sed "s/^/$host /" >> $out && rm -f $in

wc -l $out
/etc/init.d/dnsmasq restart

echo 0 > /sys/class/leds/rango:amber:wan/brightness
